### ISSUE TITLE
How to compile and install to device Qt 5.11.1?

### ISSUE THREAD

**Issue by Toni3402** [ValveSoftware/steamlink-sdk#1]
How to compile and install to device Qt 5.11.1?

**Comment by slouken** [comment]
This patch might help you, but I haven't tried it myself:
https://raw.githubusercontent.com/ValveSoftware/steamlink-sdk/master/external/qt-everywhere-src-5.11.2.patch

**Comment by Toni3402** [comment]
> This patch might help you, but I haven't tried it myself:
> https://raw.githubusercontent.com/ValveSoftware/steamlink-sdk/master/external/qt-everywhere-src-5.11.2.patch

Thank you! One more question in this issue - why in my qt app gone fonts? All other platforms builds have fonts. Maybe some steamlink platform specific? Thanks for reply anyway.
