### ISSUE TITLE
Missing kernel build instructions

### ISSUE THREAD

**Issue by cyrozap** [ValveSoftware/steamlink-sdk#10]
I've tried using `ARCH=arm DEVICE=mv88de3100_ax_bg2cd_eureka_evt_mlc_defconfig make` to build the kernel (after sourceing `setenv.sh`), but that fails with an error saying it can't find the `.config` file. It would really help to either have instructions or a script to build the kernel.

**Comment by slouken** [comment]
Kernel build instructions have been added to the README.

Thanks!
