### ISSUE TITLE
Update wpa_supplicant (KRACK Attack)

### ISSUE THREAD

**Issue by HeatedTea** [ValveSoftware/steamlink-sdk#104]
Update wpa_spplicant to prevent the recently reported KRACK attacks.

I'm not sure the Steam Link is sending anything critical over wifi, but perhaps this should still be considered.

**Comment by jerbear64** [comment]
Valve has released [beta build 643](http://steamcommunity.com/app/353380/discussions/0/1479857071249579447/) which prevents KRACK.
