### ISSUE TITLE
OpenGLES 1.1 headers are missing

### ISSUE THREAD

**Issue by elvissteinjr** [ValveSoftware/steamlink-sdk#112]
After adding them from an external source, everything links fine with the libraries which are present and appears to run as it should.

It would be beneficial to have them included with the SDK.

**Comment by slouken** [comment]
Where did you get them from? Can you create a pull request?

Thanks!

**Comment by elvissteinjr** [comment]
Sorry for the late response.

I originally grabbed the headers from my OpenPandora ARM handheld. Since I'm not 100% sure if there aren't any device specific things in those, I didn't post or mention them.

However, the headers from the khronos website seem to work just as fine, so those could be used: https://www.khronos.org/registry/OpenGL/index_es.php#headers
I did not do extensive testing, but my application runs as expected.

Regarding a pull request, the header files would usually go into "/rootfs/usr/include/GLES", but that's supposed to be a mirror of the steamlink rootfs, right?

**Comment by slouken** [comment]
These are in the SDK for the Steam Link build 644, thanks!
