### ISSUE TITLE
Disable SSH without reset

### ISSUE THREAD

**Issue by My1** [ValveSoftware/steamlink-sdk#113]
is there a way to disable SSH again when I dont need it? (important: without resetting everything obviously)

just that it isnt open and nobody can poke around without enabling it again

**Comment by parkerlreed** [comment]
````
rm `find /mnt/ -name "enable_ssh.txt"`
````

Only thing that enables it is that file.

**Comment by My1** [comment]
does mnt have more than the USB sticks, because if not, you are just removing the file from the stick, and if removing the file from the USB stick is enough it would also be enough to just powercycle it without the stick

**Comment by parkerlreed** [comment]
@My1 There's a persistent partition in /mnt where the flash drive configs get copied to. That's where the Link checks on consecutive bootups. Removing that file will make it not enable SSH on the next reboot.

**Comment by My1** [comment]
oh I see thanks for the info.
