### ISSUE TITLE
[Feature Request] Support PS3 Gasia/ Shanwan game controllers

### ISSUE THREAD

**Issue by icex** [ValveSoftware/steamlink-sdk#116]
Could you add the following patches for fake(aka cheap) PS3 controllers?
https://github.com/OpenELEC/OpenELEC.tv/tree/openelec-7.0/packages/network/bluez/patches

Or use this fork of BlueZ https://github.com/luetzel/bluez

**Comment by slouken** [comment]
These patches have been merged for Steam Link beta build 644.

Thanks!
