### ISSUE TITLE
Any chances to mount nfs/smb shares?

### ISSUE THREAD

**Issue by Schnabelriechen** [ValveSoftware/steamlink-sdk#117]
I´m trying to install the nfs-common packet onto the link to mount nfs shares. Any way to do this?

**Comment by parkerlreed** [comment]
nfs is already in the mount options 

````
# cat /proc/filesystems | awk '{print $NF}' | sed '/^$/d'
sysfs
rootfs
bdev
proc
cgroup
tmpfs
sockfs
pipefs
anon_inodefs
rpc_pipefs
devpts
ext3
ext2
ext4
squashfs
ramfs
vfat
msdos
unionfs
nfs
cifs
ntfs
fuseblk
fuse
fusectl
yaffs
yaffs2
mqueue
mtd_inodefs
oprofilefs
ubifs
````
Try mounting with `mount` to see if it works.

**Comment by Schnabelriechen** [comment]
by trying it, it gives me:

> mount monstanas:/volume1/Downloads /home/apps/retroarch/nfs
mount: mounting monstanas:/volume1/Downloads on /home/apps/retroarch/nfs failed: Connection refused
