### ISSUE TITLE
Can't ssh: connection refused

### ISSUE THREAD

**Issue by jostidetosti** [ValveSoftware/steamlink-sdk#120]
Put an empty file called `enable_ssh.txt` on a usb drive in folder `steamlink/config/system`. Plugged usb drive into Link and turned it off and on again. 

```
$ ssh 192.168.0.42
ssh: connect to host 192.168.0.42 port 22: Connection refused
```

**Comment by parkerlreed** [comment]
You need to fully power cycle (pull the plug) Standby isn't enough.

**Comment by jostidetosti** [comment]
Solved by formatting the USB thumb drive in fat instead of ext4
