### ISSUE TITLE
Update Linux kernel version for usb controllers

### ISSUE THREAD

**Issue by 1300371** [ValveSoftware/steamlink-sdk#14]
Update the current linux kernel version to support more game controllers.

For example, 
_4.15_ add support for _pdp_ controllers 
_4.12_ add support for xbox compatible controllers
and so on ...

**Comment by slouken** [comment]
These changes have already been backported into the Steam Link kernel.

**Comment by 1300371** [comment]
Really ?! ... My new _pdp Xbox One controller Royal Purple_ is not detected under SteamLink ... Works on PC. :(

**Comment by slouken** [comment]
Can you check your Steam Link system settings and make sure you're using the modern Xbox driver, not the classic one?

**Comment by 1300371** [comment]
I was already using the _modern_ driver. I switch to the classic one and it works ... 
Detected as an XInput controller. 

What the modern driver does exactly ?

**Comment by slouken** [comment]
Interesting. The modern driver includes all of the patches in Linus' kernel branch, up to and including the latest kernel release. Does your controller work with the latest Linux kernel?

**Comment by 1300371** [comment]
I will try ... and i will keep you updated
