### ISSUE TITLE
Kodi example: Need to run configure for kodi itself

### ISSUE THREAD

**Issue by Moredread** [ValveSoftware/steamlink-sdk#16]
Hey,

I tried the Kodi example, and the build stops after compiling all the dependencies, as no Makefile has been generated for Kodi itself.

When uncommenting

```
#./configure $STEAMLINK_CONFIGURE_OPTS --prefix=/home/steam/apps/kodi --disable-x11 || exit 4
```

in Line 168 it works. Is this comment left in accidentally?

**Comment by slouken** [comment]
Whoops, fixed! :)
