### ISSUE TITLE
Add Xbox One Wireless Dongle support

### ISSUE THREAD

**Issue by nschimme** [ValveSoftware/steamlink-sdk#20]
A new project has come up that allows the use of wireless dongles on Linux. Please add support to the base Steam Link image.

https://github.com/medusalix/xow

**Comment by slouken** [comment]
From that page:
NOTE: xow is still at a VERY EARLY stage of development. Do not be surprised if it does not work at all.

**Comment by slouken** [comment]
This is in build 743, thanks!

**Comment by offalynne** [comment]
@slouken any possibility of an assist on the following issue ? https://github.com/medusalix/xow/issues/5#issuecomment-586615580
