### ISSUE TITLE
Outdated Build History

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steamlink-sdk#21]
I was unsure where to post this, but I suspect github has a good chance of being read by the right people.

Whenever I notice my link update, I've been reading the changelogs located at: https://support.steampowered.com/kb_article.php?ref=8293-PDVM-4434

The current public release on my device is build 747
The build history on Valve's site only goes up to 711

Would you consider updating the build history again? Some of us actually do enjoy reading it.

**Comment by slouken** [comment]
Nice to know people are reading it. It's been updated, thanks.
