### ISSUE TITLE
Cave Express: garbled font graphics

### ISSUE THREAD

**Issue by angelosa** [ValveSoftware/steamlink-sdk#22]
I've tried to run Cave Express as a deploy test to Steam Link and all of the menu text is garbled. 
Happens with the cavepacker extension too.

![12800262_1127248103973520_3931638025709882648_n](https://cloud.githubusercontent.com/assets/9251271/13551143/0f6cff84-e330-11e5-999a-6eeb87d128ee.jpg)

**Comment by mgerhardy** [comment]
Thanks for the report - which revision of the caveexpress repository are you on? I recently switched to a font that also supports unicode.

Most likely related to https://github.com/mgerhardy/caveexpress/issues/85

Usually it helps if you delete base/$game/textures/complete.lua and rerun cmake (resp. the steamlink.sh script).

And for the sdk - maybe we should update the script to checkout a specific tag - e.g. latest tag is 2.4 (https://github.com/mgerhardy/caveexpress/tree/2.4)

**Comment by mgerhardy** [comment]
Looks like this is a problem with the small texture set - run ./cavepacker -set texturedefintiion big to solve it, too. Will continue to document the stuff in the linked ticket.

**Comment by mgerhardy** [comment]
btw: fixed in master
