### ISSUE TITLE
steamlink hevc/h265 question.

### ISSUE THREAD

**Issue by dglt1** [ValveSoftware/steamlink-sdk#25]
i apologize if this is in the wrong place, currently the mobile and rasbian builds of steamlink are able to request hevc from the pc host running steam with remote play enabled so the capability is already there, is there a way of forcing hevc/h265  pc to pc either via steam console or other means?

also, would it be possible to build the steam-link standalone app on x86/64?

thanks for your time.

**Comment by slouken** [comment]
HEVC is not available in PC to PC streaming at the moment.

The Steam Link app is available on 64-bit Linux on flathub:
https://flathub.org/apps/details/com.valvesoftware.SteamLink
