### ISSUE TITLE
Can we get the option to use a phones gyro if a controller doesnt have one? Or the ability to use both the controller and virtual controller at the same time?

### ISSUE THREAD

**Issue by Ambrotus** [ValveSoftware/steamlink-sdk#28]
Can we get the option to use the phones gyro if a controller doesnt have one?
I have a controller with out gyro, I tried to launch with Touch controller and then plug in the controller so I have access to all the touch commands. 
Any interaction with the either contoller stops the others input.
So once i enabled the virtual controllers gyro, as soon as i used the physical the gyro input stopped.
Or if i wasnt sitting still enough while using the physical controller the gyro might activate stopping all physical controller input.

There could definitly be a usecase for being able to use both the touch screen virtual controller and the physical if possible. This could give users extra buttons they could bind and use while playing as well as access to a gyro!

**Comment by slouken** [comment]
This issue reporter is for the Steam Link native SDK.

You probably want the discussion group for [Android ](https://steamcommunity.com/app/353380/discussions/4/) or [iOS](https://steamcommunity.com/app/353380/discussions/7/)
