### ISSUE TITLE
error while loading shared libraries: libmpfr.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mill1000** [ValveSoftware/steamlink-sdk#31]
## Issue 
I receive error related to libmpfr.so.4 when attempting to build anything.

e.g. trying to build the `sdl` example:
```
~/steamlink/steamlink-sdk/examples/sdl (master) $ ./build_steamlink.sh 
...
~/steamlink/steamlink-sdk/toolchain/bin/../libexec/gcc/armv7a-cros-linux-gnueabi/9.2.0/cc1: error while loading shared libraries: libmpfr.so.4: cannot open shared object file: No such file or directory
<builtin>: recipe for target 'testspriteminimal.o' failed
make: *** [testspriteminimal.o] Error 1
```
My build host is Ubuntu 20.04 LTS via WSL. 

Essentially a duplicate of #22, ~but I believe the workaround described of symlinking libmpfr.so.4 is incorrect as we want the libmpfr4 that is compiled for the target (armv7a) platform, not the host platform.~ I am incorrect, the libmpfr should be for the host system.

## Workaround
In #22, you mentioned setting LD_LIBRARY_PATH which appears to resolve the issue. I set it like so
```
export LD_LIBRARY_PATH=$TOP/toolchain/lib
```

**Comment by mill1000** [comment]
Perhaps another option is to build on a platform where libmpfr4 is available. In my case I started up another WSL instance with Ubuntu 16.04 LTS and the issue does not occur.

**Comment by slouken** [comment]
This is fixed in the latest commit. Thanks!
