### ISSUE TITLE
GDB not present in toolchain

### ISSUE THREAD

**Issue by mill1000** [ValveSoftware/steamlink-sdk#32]
As of 609d4aaccb503298e7fa9cef45e0ddc4c4afd63c (when the toolchain was upgraded to GCC 9.2.x) there is no longer a copy GDB (armv7a-cros-linux-gnueabi-gdb) in the toolchain meaning it's impossible to follow the debugging instructions in the README

**Comment by slouken** [comment]
This is fixed in https://github.com/ValveSoftware/steamlink-sdk/commit/d7fd81f912cc30cbda4f0860372316eeb5b15a48

**Comment by mill1000** [comment]
Cool. Thanks for the quick turn around.
