### ISSUE TITLE
Steam Controller constantly fires inputs when connected via Bluetooth to Chromecast with Google TV (Sabrina) device

### ISSUE THREAD

**Issue by mwp-foss** [ValveSoftware/steamlink-sdk#33]
When I connect my steam controller to the Chromecast with Google TV device via bluetooth and load the steam link application, initially it works fine. I can navigate the Big Picture mode, but once the notification comes up that the controller profile is loaded, it starts to fire the last input in rapid succession. For example, if I move the joystick to the left, once, it will continuously fire the left joystick input and move the cursor all the way to the edge of the screen preventing the steam link session from being usable.

**Comment by kisak-valve** [comment]
Hello @mwpow3ll, you'll want to post this over in the Steam Link forums for issues with [Steam Link on Android](https://steamcommunity.com/app/353380/discussions/4/) devices.
