### ISSUE TITLE
black screen using linux host

### ISSUE THREAD

**Issue by tvienneau404** [ValveSoftware/steamlink-sdk#35]
using a linux host, a black screen is present. sound and controller input is working.

multiple guest devises tested. same result

    steam link
    rpi
    android phone
    android tablet

host specifications:

    fedora 35 (also Manjaro)
    kernel 5.16
    ryzen 5600x
    32gb ram
    radeon rx6700xt

**Comment by kisak-valve** [comment]
Hello @tvienneau404, this reads like the issue being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/6148. Closing as a duplicate.
