### ISSUE TITLE
[FR] Add aarch64 Architecture to the Flatpak on Flathub

### ISSUE THREAD

**Issue by aenertia** [ValveSoftware/steamlink-sdk#36]
As per title only x86_64 architecture is available via flathub. Given the prevlance of rk3588 and similar aarch64 devices which support hvec/av1/h264 hardware decoding, providing the aarch64 build for these via the flathub portal would be useful.

**Comment by kisak-valve** [comment]
Hello @aenertia, this issue tracker is for the SDK to build stuff for the Steam Link standalone device. https://github.com/flathub/com.valvesoftware.SteamLink is a closer match, but noted at https://github.com/flathub/com.valvesoftware.SteamLink#support feature requests are not tracked there. Feel free to post this on the forums at https://steamcommunity.com/app/353380/discussions/10/.

Closing as out of scope for this issue tracker.
