### ISSUE TITLE
Feature request: WebOS support

### ISSUE THREAD

**Issue by Stijnwingens** [ValveSoftware/steamlink-sdk#38]
Steam Link is supported on many devices, but LG TV's using WebOS are sadly not amongst them. This would be a great feature allowing many more gamers to play their games on their big screen.

**Comment by kisak-valve** [comment]
Hello @Stijnwingens, this repository is a software development kit for the Steam Link standalone hardware. Feature requests for the Steam Link App to be ported to additional platforms is out of scope for this issue tracker.

The community forums at https://steamcommunity.com/app/353380/discussions/ is a better place to make this kind of request.

Closing as out of scope.
