### ISSUE TITLE
SDL_HINT_ENABLE_STEAM_CONTROLLERS defaults to '0' instead of '1'

### ISSUE THREAD

**Issue by DistractionRectangle** [ValveSoftware/steamlink-sdk#39]
I'm not exactly sure where to file this issue, as it's not exactly an issue with the steamlink-sdk, and it's not an issue with the public facing SDL repo (AFAIK), but an issue with the custom build of SDL that ships with the steamlink. If there's a better place to file this, let me know @slouken.

Issue: Per [SDL_hints.h](https://github.com/libsdl-org/SDL/blob/SDL2/include/SDL_hints.h#L391C1-L400C73), `SDL_HINT_ENABLE_STEAM_CONTROLLERS` should default to `'1'`, enabled. However, as experienced in a native steamlink app, moonlight, it has defaulted to disabled since its inception ([user reports track the issue as appearing after build 822](https://github.com/moonlight-stream/moonlight-qt/issues/697), which used an sdl 2.0.17 build, and near as I can tell this hint landed as [part of 2.0.22](https://github.com/libsdl-org/SDL/commit/d2042e1ed4e0808103168bf1bf2135601b969c4f)). It defaults to `'0'`, and steamlink native apps on builds after 822 can only see steam controllers if `SDL_ENABLE_STEAM_CONTROLLERS=1` is explicitly set as a shell/environment variable.

As far as the public facing SDL repo goes, I can only find three commits which contain `SDL_HINT_ENABLE_STEAM_CONTROLLERS`, as per `git log -p --all -G 'SDL_HINT_ENABLE_STEAM_CONTROLLERS'`:

- [First commit where the hint is documented](https://github.com/libsdl-org/SDL/commit/d2042e1ed4e0808103168bf1bf2135601b969c4f)
- [Where SDL_hints.h was sorted alphabetically](https://github.com/libsdl-org/SDL/commit/2147e7bfea0fc99fc04eef20f3a808ffc0c8865c)
- [Where it was removed as used in the development of sdl3](https://github.com/libsdl-org/SDL/commit/ad12bb4fd1a31e03e60612c94d18b95c24176664)

Aside from it's presence in `SDL_hints.h`, there are no commits where it's ever actually referenced/used via `SDL_GetHint(SDL_HINT_ENABLE_STEAM_CONTROLLERS)`, thus I am led to believe it's part of an downstream patchset for SDL maintained by Valve.

**Comment by slouken** [comment]
You're right, the Steam Link version of SDL defaulted that hint to "0". This is fixed for the next firmware update, thanks!
