### ISSUE TITLE
mame4all screen problems

### ISSUE THREAD

**Issue by HarkonXX** [ValveSoftware/steamlink-sdk#43]
MAME4ALL does not fit corretly on 16:9 1080p TV (Samsung), image is cropped on top and right, everything is moved to the right and there are huge borders on top and left.

I managed to compile install and run MAME4ALL in steam link, the problem is that the image is horribly cropped top and right and completely and displaced to the right of my TV (Samsung LED Smart TV, PAL as I'm spanish and we don't use NTSC). To be more precise I am seeing the interface on the lower right border of the screen and with parts missing.

There is no way of controlling resolution from mame.cfg as it only includes resolution for vertorial games, and the option to change border is completely useless (tried yes, no, 24, 0, with no avail)

I have started MAME4ALL even from an SSH terminal and it starts giving me more info, I see a funtion trying to resscale from 1280x720 to 1920x1080 but must be in the binary. Obviously that function is in the code previous compiling so maybe changing something in the code before the build could solve this.

I'm linux expert and have some c and c++ skils but need some help to see where I have to change anything without breaking my TV

**Comment by slouken** [comment]
This is fixed in build 564, thanks!
