### ISSUE TITLE
Please keep default master branch files to bare minimum

### ISSUE THREAD

**Issue by mdeguzis** [ValveSoftware/steamlink-sdk#44]
Please set default master branch to bare minimum. The git checkout is a whooping 6.5G. The examples/extras should be added in as an examples branch or a submodule to say "steamlink-sdk-examples" and so, for instance. Anything not required for building should be stripped from master Several examples include full source code instead of cloning a fork of the project, which adds to the size.

```
desktop@debian-testing:/mnt/bulk-storage$ du -hd 1 /mnt/bulk-storage/
6.5G    /mnt/bulk-storage/steamlink-sdk
```

On a VPS with a fast network connection, I sometimes get this when doing the simplest of tasks like `git status`:

```
It took 29.14 seconds to enumerate untracked files. 'status -uno'
may speed it up, but you have to be careful not to forget to add
new files yourself (see 'git help status').
nothing to commit, working directory clean
```

**Comment by slouken** [comment]
The examples directory is only 122 MB, and splitting them up wouldn't help the size much. There are currently no plans to split the master branch, but you're welcome to fork and split it yourself.
