### ISSUE TITLE
Please update firmware files with the ones officialy rolled-out to steam links

### ISSUE THREAD

**Issue by HarkonXX** [ValveSoftware/steamlink-sdk#45]
Actual firmware files are from version 548 and the latest and official firmware is 554 from november the 7th of 2016, that's more than 3 weeks ago.

Shouldn't the files be paired?

**Comment by slouken** [comment]
Updated as of build 560, thanks!

**Comment by Schnabelriechen** [comment]
Meanwhile the 640 version is out and the sdk still on 630, any chances for update?
