### ISSUE TITLE
How to create custom controller mappings for the Steam Link

### ISSUE THREAD

**Issue by slouken** [ValveSoftware/steamlink-sdk#46]
Grab the Steam Link SDK from here:
https://github.com/ValveSoftware/steamlink-sdk

Then grab the source to SDL from here:
http://www.libsdl.org/tmp/SDL-2.0.zip

Build the controllermap test program and copy it and the BMP files from the test directory to the Steam Link.

Then kill the Steam Link shell:
killall app_run.sh shell

Then plug in your controller and run controllermap 0 to bring up the mapping UI and create a mapping string.

Post the mapping string so we can add it to the official firmware, and you can use it locally by adding it to the file /etc/controller_map.txt, which doesn't exist by default.

Cheers!

**Comment by parkerlreed** [comment]
Couldn't this be closed/updated now that there is native remapping built-in that saves to the same file?

**Comment by slouken** [comment]
Yup!
