### ISSUE TITLE
lzo lib?

### ISSUE THREAD

**Issue by mtdeguzis** [ValveSoftware/steamlink-sdk#47]
I am working towards porting Open Plex Home Theater to the Steam Link. I am having trouble locating lzo2 in the SDK. I was able to set the other libs ok so far. I see [libpng](https://github.com/ValveSoftware/steamlink-sdk/tree/master/rootfs/usr/include) and many others, but not lzo.

```
CMake Error at plex/CMakeModules/CMakeFunctions.cmake:178 (message):
  Missing LZO2
Call Stack (most recent call first):
  plex/CMakeModules/PlatformConfigSTEAMLINK.cmake:45 (plex_find_package)
  plex/CMakeModules/CMakeConfig.cmake:82 (include)
  CMakeLists.txt:55 (include)


-- Configuring incomplete, errors occurred!
```

Build files: https://github.com/ProfessorKaos64/steamlink-sdk/tree/openpht/examples/openpht

**Comment by slouken** [comment]
lzo isn't part of the SDK. You're welcome to build it yourself though.
