### ISSUE TITLE
What was the point in locking down bootloader and kernel?

### ISSUE THREAD

**Issue by julienbenjamin** [ValveSoftware/steamlink-sdk#6]
I wanted to install whatever custom Linux distribution I would have built myself but since the kernel needs to be signed by ValveSoftware and the bootloader but it is impossible to do so.

I wanted to know what was the point, and if you would plan to change this in the future?

I know this is a long shot, but it is worth asking.

**Comment by slouken** [comment]
It's a legal requirement in our contract with Marvell.

**Comment by dxgldotorg** [comment]
Does that agreement in any way go against any laws, for example antitrust laws?

**Comment by zfkdnop** [comment]
> Does that agreement in any way go against any laws, for example antitrust laws?

No. This sort of restriction is very common in IT.

Why would the lawyers of two multi-million-dollar companies write and agree to a contract that was drawn up on unstable and illegal grounds?
