### ISSUE TITLE
GCC toolchain depends on Python 2

### ISSUE THREAD

**Issue by brycied00d** [ValveSoftware/steamlink-sdk#6]
It should be noted that the script `toolchain/usr/x86_64-pc-linux-gnu/armv7a-cros-linux-gnueabi/gcc-bin/4.9.x-google/armv7a-cros-linux-gnueabi-gcc` calls `/usr/bin/python` in the shebang. If your system `/usr/bin/python` is Python 3, the script will error out for invalid syntax.
```
  File "/path/to/steamlink-sdk/toolchain/bin/../usr/x86_64-pc-linux-gnu/armv7a-cros-linux-gnueabi/gcc-bin/4.9.x-google/armv7a-cros-linux-gnueabi-gcc", line 352
    os.chmod(log_file, 0666)
                          ^
SyntaxError: invalid token
```

Python [PEP-0394](https://www.python.org/dev/peps/pep-0394/) recommends that scripts that require Python 2 should call `/usr/bin/python2`
> in preparation for an eventual change in the default version of Python, Python 2 only scripts should either be updated to be source compatible with Python 3 or else to use python2 in the shebang line.

```diff
index cac4659..c487c1e 100755
--- a/toolchain/usr/x86_64-pc-linux-gnu/armv7a-cros-linux-gnueabi/gcc-bin/4.9.x-google/sysroot_wrapper.hardened
+++ b/toolchain/usr/x86_64-pc-linux-gnu/armv7a-cros-linux-gnueabi/gcc-bin/4.9.x-google/sysroot_wrapper.hardened
@@ -1,4 +1,4 @@
-#!/usr/bin/python
+#!/usr/bin/python2
 
 # Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
 # Use of this source code is governed by a BSD-style license that can be
```

There are references to `/usr/bin/python` in many of the external/ dependencies, however I have not tried building those dependencies and don't know if those scripts are compatible with Python 3.

**Comment by slouken** [comment]
Fixed, thanks!
