### ISSUE TITLE
SDL applications ignore audio output preference

### ISSUE THREAD

**Issue by parkerlreed** [ValveSoftware/steamlink-sdk#60]
I just now noticed that when I have a Bluetooth headset connected, SDL applications still play out of HDMI. Only the launcher interface and in-game route correctly

From what I recall this worked correctly with Pulseaudio but since everything has moved to ALSA, it seems to not work anymore.

EDIT: Oh I just realized the Bluetooth headset is in fact using Pulse. Hmm

**Comment by slouken** [comment]
The automatic hotplug switching isn't implemented in SDL, but specifying USB and Bluetooth in the audio settings should work in the next beta build.

**Comment by parkerlreed** [comment]
Thanks. I'm not hotplugging but the audio just isn't going to the expected source. Bluetooth connection stays active but audio just goes out HDMI. I'll see if that clears up in the update.

**Comment by parkerlreed** [comment]
Fixed as of https://github.com/ValveSoftware/steamlink-sdk/commit/57aacbe7654b5e385bed00a679bb2f5cea2eeb74

Thanks @slouken! Also neat to know I can throw libs in that directory to test.

**Comment by slouken** [comment]
Great, I'm glad it works. :)
