### ISSUE TITLE
Kodi compile tries to create /home/kodi-deps

### ISSUE THREAD

**Issue by MartenvanWezel** [ValveSoftware/steamlink-sdk#63]
Trying to create some directory in /home on any unix system is typically bad form. Why is the build process not contained in the directory we are compiling in?

**Comment by slouken** [comment]
It should be creating kodi-deps inside the Marvell SDK. It installs lots of third party libraries that may be useful for other packages being built for the Steam Link.

I just pushed a change to make sure that it's actually in the SDK root before trying to do that though.
