### ISSUE TITLE
Are udev Rules Even Triggert?

### ISSUE THREAD

**Issue by retuxx** [ValveSoftware/steamlink-sdk#68]
I'm currently working on a simple-to-use automount script that is based on debian's  [usbmount](https://usbmount.alioth.debian.org/) package. The script works perfectly by itself but running it using udev rules doesn't work. I even tried to add a very simple rule mounting /dev/block/sda1 on any `Add` action. However, the rules is never triggered. My concern is that udev isn't working on Steam Link currently. Correct me please if I am wrong.

**Comment by slouken** [comment]
udev doesn't currently run on Steam Link.

**Comment by retuxx** [comment]
Are there plans to udev in future?
