### ISSUE TITLE
Can we have kernel updated to something closer to mainline?

### ISSUE THREAD

**Issue by tpruzina** [ValveSoftware/steamlink-sdk#70]
Steamlink runs on 3.8.13 which is [last of the 3.8.x stable kernels and was released/deprecated on 03/2013](http://lkml.iu.edu/hypermail/linux/kernel/1305.1/02171.html).
Since we can't push our own kernels due to big fat warning in README.md, could you please bring steamlink kernel to some [supported stable version](https://www.kernel.org/) (so that we also get [security fixes](http://www.cvedetails.com/vulnerability-list.php?vendor_id=33&product_id=47&version_id=147600&page=1&hasexp=0&opdos=0&opec=0&opov=0&opcsrf=0&opgpriv=0&opsqli=0&opxss=0&opdirt=0&opmemc=0&ophttprs=0&opbyp=0&opfileinc=0&opginf=0&cvssscoremin=0&cvssscoremax=0&year=0&month=0&cweid=0&order=3&trc=171&sha=439fa7f328f5faea58755bb592166d6999e1a64e)) such as 4.4?

>gregkh at linuxfoundation, May 11, 2013, 2:46 PM 
>>NOTE, this is the LAST 3.8.y kernel release, please move to the 3.9.y
kernel series at this time. It is end-of-life, dead, gone, buried, and
put way behind us never to be spoken of again. Seriously, move on, it's
just not worth it anymore. 
>>And for that specific two-letter hardware company that was insisting in
public that I would be maintaining the 3.8.y kernel as a long-term
kernel so that "you will do our maintenance work for us, for free,"
please see figure one.

**Comment by slouken** [comment]
There are currently no plans to update the kernel. Please let us know if there are any remote security vulnerabilities that affect the Steam Link.
