### ISSUE TITLE
QT compiled programs not runnning anymore

### ISSUE THREAD

**Issue by thecosmicslug** [ValveSoftware/steamlink-sdk#77]
Since the move to qt5.8 I am still unable to get my programs to run. Ive added LFS instructions and got compilation to work again, but the program segfaults on the link. I have tried a clean clone of the sdk, and even a factory reset and check for updates on the link. the error messages seem to be relating to qt5.4 still, is there something I need to change in my project?

`/usr/local/Qt-5.4.1/lib/libQt5Core.so.5: version `Qt_5' not found
/usr/local/Qt-5.4.1/lib/libQt5Gui.so.5: version `Qt_5' not found 
/usr/local/Qt-5.4.1/lib/libQt5Widgets.so.5: version `Qt_5' not found`

**Comment by slouken** [comment]
You need Steam Link build 594 or newer, which is not available yet.

**Comment by thecosmicslug** [comment]
Ah! Glad its nothing my end, thanks for letting me know slouken, Looking forward to playing with the next update!

**Comment by slouken** [comment]
Build 597 is now available. :)

**Comment by parkerlreed** [comment]
@slouken Home directory IO fix also included?

**Comment by slouken** [comment]
Yes, it should work much better now.

**Comment by parkerlreed** [comment]
@slouken Woohoo! Just tested with RetroArch and it still hung for a second but I think it's just a zip with a lot of small files. Extracted successfully and worked.
