### ISSUE TITLE
Bootloader private key for kernel signing

### ISSUE THREAD

**Issue by Echelon9** [ValveSoftware/steamlink-sdk#8]
Following the decision to [discontinue production of the physical Steam Link](https://steamcommunity.com/games/353380/announcements/detail/2533733726684325037), are you able to revisit the possibility of releasing a private key - or a service that would sign provided binary kernels without communicating that private key?

This would allow customers to sign their own closer-to-mainline kernels which would be accepted by the bootloader on these Marvell SoCs.

Does the contractual prohibition continue indefinitely after the conclusion of the production period?

**Comment by slouken** [comment]
Yes, it does.
