### ISSUE TITLE
360 gamepad controls mouse for Metro apps

### ISSUE THREAD

**Issue by BlinksTale** [ValveSoftware/steamlink-sdk#8]
Copying this issue over from SteamOS since it sounds like this is a better place for it:

Streaming Windows 10 metro apps will treat a 360 gamepad as though it is mouse input instead. This causes problems for titles like Minecraft Win 10 ed and Xbox One streaming through Steam, though it is still useful for Microsoft Solitaire Collection. It would be great to be able to turn this on and off.

I'd like to try poking through the source code and seeing if I can figure out the problem on my own to help contribute, but aside from checking every file, I'm not sure where to start. Advice on where in the code controllers are handled would help a great deal.

**Comment by not83** [comment]
Is this a problem with the steam link sdk

**Comment by BlinksTale** [comment]
That's what I'm trying to find out! Streaming is a two side problem: host and client. Steam Link inherently will cover a lot of client end stuff, like controller input, so it depends on both where the controller is turned into mouse input (host vs client) and whether the SDK handles that or if it's even lower level than that.

It might be within the realm of Steam Link's SDK, and I don't have a better place to turn, so worth a shot so long as I'm pursuing this issue.

**Comment by not83** [comment]
There is this place

https://steamcommunity.com/groups/homestream/discussions

I think we wait to see what Valve thinks. If they are reading this then
there is no place to report streaming issues

On 16 January 2016 at 10:11, Brian Handy <notifications@github.com> wrote:

> That's what I'm trying to find out! Streaming is a two side problem: host
> and client. Steam Link inherently will cover a lot of client end stuff,
> like controller input, so it depends on both where the controller is turned
> into mouse input (host vs client) and whether the SDK handles that or if
> it's even lower level than that.
>
> It might be within the realm of Steam Link's SDK, and I don't have a
> better place to turn, so worth a shot so long as I'm pursuing this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ValveSoftware/steamlink-sdk/issues/8#issuecomment-172093508>
> .
>



-- 
Joshua Murphy

**Comment by BlinksTale** [comment]
@not83 I already tried that sadly, the replies were just the community, and not helpful sadly:

https://steamcommunity.com/app/353380/discussions/0/451848855026871092/

Do you have any other ideas on where to go with this?
