### ISSUE TITLE
Steam Link Kodi Error

### ISSUE THREAD

**Issue by Gramps** [ValveSoftware/steamlink-sdk#87]
The build seems to compile fine except I do not get the "Build complete!" message.  It just kind of ends and the steamlink folder is there.  But when I try to move it to a USB drive I get the following:
```
Error while copying “audiodecoder.2sf.so.17.2”.
Filesystem does not support symbolic links
```
This happens for a few files that are apparently symbolic links.  Not sure if it is because it is formatted to fat32 or not.  Also not sure if the build isn't complete hence the lack of "Build complete!" at the end.  However, there are no errors that I can see anywhere.

UPDATE:  Turns out there were errors buried in there.  The dreaded:
```
Teletext.h:29:23: fatal error: freetype/freetype.h: No such file or directory
 #include FT_FREETYPE_H
```
Even though FreeType is installed in the system.

**Comment by thecosmicslug** [comment]
can confirm I got this error the last time I tried to compile kodi as well

**Comment by jonesmz** [comment]
If you add

export PC_FREETYPE_INCLUDEDIR="${DEPS_INSTALL_PATH}/include/freetype2/"
export FREETYPE2_CFLAGS="-I${DEPS_INSTALL_PATH}/include -I${PC_FREETYPE_INCLUDEDIR}"


prior to the ./configure $STEAMLINK_CONFIGURE_OPTS .......

line, it'll get past this error

**Comment by jonesmz** [comment]
Something like this... though, I edited a few lines of the patch, so grain of salt, and all.


diff --git a/examples/kodi/build_steamlink.sh b/examples/kodi/build_steamlink.sh
index 7d1e796944..ca841441f0 100755
--- a/examples/kodi/build_steamlink.sh
+++ b/examples/kodi/build_steamlink.sh
@@ -207,6 +207,8 @@ export CFLAGS CXXFLAGS CPPFLAGS
 export LD AR AS NM STRIP RANLIB OBJDUMP
 export PYTHON_VERSION PYTHON_CPPFLAGS PYTHON_LDFLAGS PYTHON_SITE_PKG PYTHON_NOVERSIONCHECK NATIVE_ROOT
 export UDEV_CFLAGS="-I${DEPS_INSTALL_PATH}/include"
+export PC_FREETYPE_INCLUDEDIR="${DEPS_INSTALL_PATH}/include/freetype2/"
+export FREETYPE2_CFLAGS="-I${DEPS_INSTALL_PATH}/include -I${PC_FREETYPE_INCLUDEDIR}"
 export UDEV_LIBS=-ludev
 export CEC_CFLAGS="-I${DEPS_INSTALL_PATH}/include"
 export CEC_LIBS=-lcec

**Comment by Gramps** [comment]
Sounds good. I'll try this when I get back into Linux.  Cheers!

**Comment by Gramps** [comment]
Yep, that fixed it, sir!  You should get them to add that as a fix.  Thanks again!

**Comment by kisak-valve** [comment]
Could someone submit a pull request with this adjustment?

**Comment by Gramps** [comment]
Will do.  Give me about 30 minutes...

**Comment by Gramps** [comment]
Done and submitted!
