### ISSUE TITLE
Kodi: Invalid use of incomplete type 'class CEGLNativeType'

### ISSUE THREAD

**Issue by jonesmz** [ValveSoftware/steamlink-sdk#93]
EGLWrapper.cpp: In function 'bool {anonymous}::CorrectGuess(CEGLNativeType*, const string&)':
EGLWrapper.cpp:66:13: error: invalid use of incomplete type 'class CEGLNativeType'
     if(guess->CheckCompatibility())
             ^
In file included from EGLWrapper.cpp:43:0:
EGLWrapper.h:28:7: error: forward declaration of 'class CEGLNativeType'
 class CEGLNativeType;
       ^
EGLWrapper.cpp:68:34: error: invalid use of incomplete type 'class CEGLNativeType'
       if (implementation == guess->GetNativeName() ||
                                  ^
In file included from EGLWrapper.cpp:43:0:
EGLWrapper.h:28:7: error: forward declaration of 'class CEGLNativeType'
 class CEGLNativeType;
       ^
EGLWrapper.cpp: In member function 'bool CEGLWrapper::Initialize(const string&)':
EGLWrapper.cpp:110:7: error: expected primary-expression before ')' token
       )
       ^
EGLWrapper.cpp:114:18: error: invalid use of incomplete type 'class CEGLNativeType'
     m_nativeTypes->Initialize();
                  ^
In file included from EGLWrapper.cpp:43:0:
EGLWrapper.h:28:7: error: forward declaration of 'class CEGLNativeType'
 class CEGLNativeType;
       ^
EGLWrapper.cpp: In member function 'bool CEGLWrapper::Destroy()':
EGLWrapper.cpp:126:16: error: invalid use of incomplete type 'class CEGLNativeType'
   m_nativeTypes->Destroy();
                ^
In file included from EGLWrapper.cpp:43:0:
EGLWrapper.h:28:7: error: forward declaration of 'class CEGLNativeType'
 class CEGLNativeType;
       ^
EGLWrapper.cpp:128:10: warning: possible problem detected in invocation of delete operator: [-Wdelete-incomplete]
   delete m_nativeTypes;
          ^
EGLWrapper.cpp:128:10: warning: invalid use of incomplete type 'class CEGLNativeType'
In file included from EGLWrapper.cpp:43:0:
EGLWrapper.h:28:7: warning: forward declaration of 'class CEGLNativeType'
 class CEGLNativeType;
       ^
EGLWrapper.cpp:128:10: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined
   delete m_nativeTypes;
          ^
EGLWrapper.cpp: In member function 'std::string CEGLWrapper::GetNativeName()':
EGLWrapper.cpp:136:25: error: invalid use of incomplete type 'class CEGLNativeType'
     return m_nativeTypes->GetNativeName();
                         ^
In file included from EGLWrapper.cpp:43:0:
EGLWrapper.h:28:7: error: forward declaration of 'class CEGLNativeType'
 class CEGLNativeType;
       ^
EGLWrapper.cpp: In member function 'bool CEGLWrapper::CreateNativeDisplay()':
EGLWrapper.cpp:145:23: error: invalid use of incomplete type 'class CEGLNativeType'
   return m_nativeTypes->CreateNativeDisplay();
                       ^
In file included from EGLWrapper.cpp:43:0:
EGLWrapper.h:28:7: error: forward declaration of 'class CEGLNativeType'
 class CEGLNativeType;
       ^
EGLWrapper.cpp: In member function 'bool CEGLWrapper::CreateNativeWindow()':
EGLWrapper.cpp:153:23: error: invalid use of incomplete type 'class CEGLNativeType'
   return m_nativeTypes->CreateNativeWindow();
                       ^
In file included from EGLWrapper.cpp:43:0:
EGLWrapper.h:28:7: error: forward declaration of 'class CEGLNativeType'
 class CEGLNativeType;
       ^
EGLWrapper.cpp: In member function 'void CEGLWrapper::DestroyNativeDisplay()':
EGLWrapper.cpp:159:18: error: invalid use of incomplete type 'class CEGLNativeType'
     m_nativeTypes->DestroyNativeDisplay();
                  ^
In file included from EGLWrapper.cpp:43:0:
EGLWrapper.h:28:7: error: forward declaration of 'class CEGLNativeType'
 class CEGLNativeType;
       ^
EGLWrapper.cpp: In member function 'void CEGLWrapper::DestroyNativeWindow()':
EGLWrapper.cpp:165:18: error: invalid use of incomplete type 'class CEGLNativeType'
     m_nativeTypes->DestroyNativeWindow();
                  ^
In file included from EGLWrapper.cpp:43:0:
EGLWrapper.h:28:7: error: forward declaration of 'class CEGLNativeType'
 class CEGLNativeType;
       ^
EGLWrapper.cpp: In member function 'bool CEGLWrapper::SetNativeResolution(RESOLUTION_INFO&)':
EGLWrapper.cpp:172:23: error: invalid use of incomplete type 'class CEGLNativeType'
   return m_nativeTypes->SetNativeResolution(res);
                       ^
In file included from EGLWrapper.cpp:43:0:
EGLWrapper.h:28:7: error: forward declaration of 'class CEGLNativeType'
 class CEGLNativeType;
       ^
EGLWrapper.cpp: In member function 'bool CEGLWrapper::ProbeResolutions(std::vector<RESOLUTION_INFO>&)':
EGLWrapper.cpp:179:23: error: invalid use of incomplete type 'class CEGLNativeType'
   return m_nativeTypes->ProbeResolutions(resolutions);
                       ^
In file included from EGLWrapper.cpp:43:0:
EGLWrapper.h:28:7: error: forward declaration of 'class CEGLNativeType'
 class CEGLNativeType;
       ^
EGLWrapper.cpp: In member function 'bool CEGLWrapper::GetPreferredResolution(RESOLUTION_INFO*)':
EGLWrapper.cpp:187:23: error: invalid use of incomplete type 'class CEGLNativeType'
   return m_nativeTypes->GetPreferredResolution(res);
                       ^
In file included from EGLWrapper.cpp:43:0:
EGLWrapper.h:28:7: error: forward declaration of 'class CEGLNativeType'
 class CEGLNativeType;
       ^
EGLWrapper.cpp: In member function 'bool CEGLWrapper::GetNativeResolution(RESOLUTION_INFO*)':
EGLWrapper.cpp:195:23: error: invalid use of incomplete type 'class CEGLNativeType'
   return m_nativeTypes->GetNativeResolution(res);
                       ^
In file included from EGLWrapper.cpp:43:0:
EGLWrapper.h:28:7: error: forward declaration of 'class CEGLNativeType'
 class CEGLNativeType;
       ^
EGLWrapper.cpp: In member function 'bool CEGLWrapper::ShowWindow(bool)':
EGLWrapper.cpp:203:23: error: invalid use of incomplete type 'class CEGLNativeType'
   return m_nativeTypes->ShowWindow(show);
                       ^
In file included from EGLWrapper.cpp:43:0:
EGLWrapper.h:28:7: error: forward declaration of 'class CEGLNativeType'
 class CEGLNativeType;
       ^
EGLWrapper.cpp: In member function 'bool CEGLWrapper::GetQuirks(int*)':
EGLWrapper.cpp:210:26: error: invalid use of incomplete type 'class CEGLNativeType'
   *quirks = m_nativeTypes->GetQuirks();
                          ^
In file included from EGLWrapper.cpp:43:0:
EGLWrapper.h:28:7: error: forward declaration of 'class CEGLNativeType'
 class CEGLNativeType;
       ^
EGLWrapper.cpp: In member function 'bool CEGLWrapper::InitDisplay(void**)':
EGLWrapper.cpp:222:21: error: invalid use of incomplete type 'class CEGLNativeType'
   if (!m_nativeTypes->GetNativeDisplay((XBNativeDisplayType**)&nativeDisplay))
                     ^
In file included from EGLWrapper.cpp:43:0:
EGLWrapper.h:28:7: error: forward declaration of 'class CEGLNativeType'
 class CEGLNativeType;
       ^
EGLWrapper.cpp:222:41: error: 'XBNativeDisplayType' was not declared in this scope
   if (!m_nativeTypes->GetNativeDisplay((XBNativeDisplayType**)&nativeDisplay))
                                         ^
EGLWrapper.cpp:222:62: error: expected primary-expression before ')' token
   if (!m_nativeTypes->GetNativeDisplay((XBNativeDisplayType**)&nativeDisplay))
                                                              ^
EGLWrapper.cpp: In member function 'bool CEGLWrapper::CreateSurface(EGLDisplay, EGLConfig, void**)':
EGLWrapper.cpp:293:21: error: invalid use of incomplete type 'class CEGLNativeType'
   if (!m_nativeTypes->GetNativeWindow((XBNativeWindowType**)&nativeWindow))
                     ^
In file included from EGLWrapper.cpp:43:0:
EGLWrapper.h:28:7: error: forward declaration of 'class CEGLNativeType'
 class CEGLNativeType;
       ^
EGLWrapper.cpp:293:40: error: 'XBNativeWindowType' was not declared in this scope
   if (!m_nativeTypes->GetNativeWindow((XBNativeWindowType**)&nativeWindow))
                                        ^
EGLWrapper.cpp:293:60: error: expected primary-expression before ')' token
   if (!m_nativeTypes->GetNativeWindow((XBNativeWindowType**)&nativeWindow))
                                                            ^
EGLWrapper.cpp: In member function 'bool CEGLWrapper::CreateNativeDisplay()':
EGLWrapper.cpp:146:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
EGLWrapper.cpp: In member function 'bool CEGLWrapper::CreateNativeWindow()':
EGLWrapper.cpp:154:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
EGLWrapper.cpp: In member function 'bool CEGLWrapper::SetNativeResolution(RESOLUTION_INFO&)':
EGLWrapper.cpp:173:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
EGLWrapper.cpp: In member function 'bool CEGLWrapper::ProbeResolutions(std::vector<RESOLUTION_INFO>&)':
EGLWrapper.cpp:180:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
EGLWrapper.cpp: In member function 'bool CEGLWrapper::GetPreferredResolution(RESOLUTION_INFO*)':
EGLWrapper.cpp:188:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
EGLWrapper.cpp: In member function 'bool CEGLWrapper::GetNativeResolution(RESOLUTION_INFO*)':
EGLWrapper.cpp:196:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
EGLWrapper.cpp: In member function 'bool CEGLWrapper::ShowWindow(bool)':
EGLWrapper.cpp:204:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[1]: *** [../../../Makefile.include:98: EGLWrapper.o] Error 1
make: *** [Makefile:436: xbmc/windowing/egl/windowing_egl.a] Error 2
make: *** Waiting for unfinished jobs....
CPP     xbmc/input/joysticks/JoystickMonitor.o
CPP     xbmc/input/joysticks/generic/InputHandling.o
CPP     xbmc/input/joysticks/JoystickTranslator.o
CPP     xbmc/dialogs/GUIDialogTextViewer.o
CPP     xbmc/input/joysticks/KeymapHandler.o
CPP     xbmc/input/joysticks/RumbleGenerator.o
LinuxInputDevices.cpp: In member function 'void CLinuxInputDevice::SetLed(int, int)':
LinuxInputDevices.cpp:822:35: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(m_fd, &levt, sizeof(levt));
                                   ^
LinuxInputDevices.cpp: In member function 'void CLinuxInputDevice::SetupKeyboardAutoRepeat(int)':
LinuxInputDevices.cpp:917:37: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
     write(fd, &event, sizeof(event));
                                     ^
LinuxInputDevices.cpp:923:37: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
     write(fd, &event, sizeof(event));
                                     ^
AR      xbmc/pvr/channels/pvrchannels.a
CPP     xbmc/dialogs/GUIDialogVolumeBar.o
CPP     xbmc/filesystem/SpecialProtocolDirectory.o
AR      xbmc/input/joysticks/generic/input_joysticks_generic.a
AR      xbmc/view/view.a
CPP     xbmc/filesystem/SpecialProtocolFile.o
CPP     xbmc/filesystem/StackDirectory.o
CPP     xbmc/video/dialogs/GUIDialogTeletext.o
CPP     xbmc/dialogs/GUIDialogYesNo.o
AR      xbmc/input/linux/input_linux.a
CPP     xbmc/video/dialogs/GUIDialogVideoBookmarks.o
CPP     xbmc/video/dialogs/GUIDialogVideoInfo.o
CPP     xbmc/video/dialogs/GUIDialogVideoOSD.o
CPP     xbmc/pvr/dialogs/GUIDialogPVRTimerSettings.o
CPP     xbmc/filesystem/udf25.o
CPP     xbmc/filesystem/UDFDirectory.o
CPP     xbmc/filesystem/UDFFile.o
CPP     xbmc/filesystem/VideoDatabaseDirectory.o
CPP     xbmc/pvr/PVRActionListener.o
CPP     xbmc/filesystem/VirtualDirectory.o
CPP     xbmc/windows/GUIWindowHome.o
CPP     xbmc/filesystem/XbtDirectory.o
AR      xbmc/input/joysticks/input_joysticks.a
CPP     xbmc/filesystem/XbtFile.o
CPP     xbmc/filesystem/XbtManager.o
CPP     xbmc/filesystem/ZeroconfDirectory.o
CPP     xbmc/filesystem/ZipDirectory.o
CPP     xbmc/filesystem/ZipFile.o
CPP     xbmc/filesystem/ZipManager.o
CPP     xbmc/filesystem/NFSFile.o
CPP     xbmc/filesystem/NFSDirectory.o
CPP     xbmc/windows/GUIWindowLoginScreen.o
CPP     xbmc/filesystem/BlurayDirectory.o
ZipFile.cpp: In member function 'virtual int64_t XFILE::CZipFile::Seek(int64_t, int)':
ZipFile.cpp:199:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           if (Read(buf.get(),iToRead) != iToRead)
                                       ^
ZipFile.cpp:218:38: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (Read(buf.get(), iToRead) != iToRead)
                                      ^
ZipFile.cpp:231:38: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (Read(buf.get(), iToRead) != iToRead)
                                      ^
CPP     xbmc/filesystem/BlurayFile.o

**Comment by jonesmz** [comment]
In an attempt to disable the parts of Kodi that use this, I modified the configuration line to this

./configure $STEAMLINK_CONFIGURE_OPTS --prefix=/home/apps/kodi --disable-x11 --disable-gl --disable-vdpau --disable-vaapi --enable-sdl --disable-gles --disable-openmax --disable-dbus --disable-alsa --disable-samba --disable-ssh --enable-nf
s --disable-airplay --disable-airtunes --disable-upnp --disable-avahi --disable-mdnsembedded --disable-non-free --disable-mysql --disable-webserver --disable-optical-drive --disable-libxslt --disable-lirc || exit 4


It didn't change anything

**Comment by jonesmz** [comment]
Note:

This is on Gentoo.

It's likely that the kodi build script is relying on a system dependency that isn't specified or checked for, instead of pulling the relevant dependency down inside the build root.

**Comment by zooxy** [comment]
Apparently PKG_CHECK_MODULES in configure.ac can't resolve sdl2 and some other libraries.
For whatever reason PKG_CONFIG_LIBDIR doesn't include the *.pc files for sdl2. Modifying PKG_CONFIG_LIBDIR to include said *.pc files fixes the compile errors, but kodi still crashes when launched on the steam link

**Comment by jonesmz** [comment]
@zooxy  Could you show me which line you modified and how? I'd like to give it a shot on my system

**Comment by zooxy** [comment]
```
#
# Finally build Kodi
# 
source "${MARVELL_SDK_PATH}/setenv.sh" || exit 1
OLD_PKG_CONFIG_LIBDIR=$PKG_CONFIG_LIBDIR
source "${DEPS_CONFIG_SITE}"
export PKG_CONFIG_LIBDIR="${PKG_CONFIG_LIBDIR}:${OLD_PKG_CONFIG_LIBDIR}"
```

in build_steamlink.sh line ~200

**Comment by jonesmz** [comment]
@zooxy 

Yep, I was able to compile with your change.

Want me to make a pull request to that effect? Or would you like to?

**Comment by TeamERHUC** [comment]
Can you launch kodi on the steam link without crashing?

Feel free to make a pull request - I have no idea how any of this git stuff works

**Comment by zooxy** [comment]
Can you launch kodi on the steam link without crashing?

Feel free to make a pull request -  I have no idea how any of this git stuff works

**Comment by jonesmz** [comment]
I have not had an opportunity yet. I probably won't be able to try until tomorrow.

I will make a pull request with your changes.

**Comment by jonesmz** [comment]
The Kodi that I compiled today using your fix launches without crashing. Nice :-)

**Comment by pdrobek** [comment]
Do you know how to patch kodi itself to avoid this issue?

**Comment by jonesmz** [comment]
@pdrobek Don't think it's an issue with kodi itself. It's an issue with the build root for the steamlink sdk.

The problem should be fixed in the latest master branch of this repository anyway? Why did you want to modify Kodi itself? Are you still having problems?

**Comment by pdrobek** [comment]
Yep, im unable to compile whole 17.x tree, now i downgrade to 16.1 and i have to see if this move is correct or not. Some ppl said that i need to upgrade my toolchain (gcc4.94) to at least 5.x

**Comment by jonesmz** [comment]
Hrmm, yea sorry I really wouldn't know where to start looking.

Are you running into errors that look substantially similar to what I posted at the start of this issue?


Gcc 4.9.4 *does* have some substantial problems with regards to c++14 compliance. It's possible that they simply are using language features that gcc 4.9.4 doesn't support properly, or at all... You might be out of luck if that's the case.

**Comment by pdrobek** [comment]
thx for assistance :-)
